datasets:
  chv:
    classes:
      0:
        class_name: Person
        inner_classes:
        - 0
      1:
        class_name: Vest
        inner_classes:
        - 1
      2:
        class_name: Helmet
        inner_classes:
        - 2
        - 5
  safety_vest:
    classes:
      0:
        class_name: Helmet
        inner_classes:
        - 0
      1:
        class_name: Vest
        inner_classes:
        - 1
split:
  indexing_path: /home/maksim/Desktop/Projects/neft_project/yolov7_helmet_detection/src/dataset/last_indexes/indexing_22-11-01_23-38-24.yaml
  parts:
    test: 0.05
    train: 0.8
    valid: 0.15
  random_state: 15
